#!groovy
@Library('common-api') _

pipeline {

    agent any

    environment {
        APP_REPO_URL = 'https://github.com/jinho-yoo-jack/fastcampus-ci-cd.git'
        GITHUB_CREDENTIAL_ID = 'github-access-token'
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-access-key') // jenkins에 등록해 놓은 docker hub credentials 이름
        DOCKERHUB_REPOSITORY = "jhy7342/cicd-study"  //docker hub id와 repository 이름
        TARGET_HOST = "ec2-18-219-194-210.us-east-2.compute.amazonaws.com"
    }

    stages {
        stage('Checkout Git As TagName'){
            steps {
                sh "pwd"
                echo "git clone"
                script {
                    try {
                        if("${env.TAG_NAME}" == "origin/master"){
                            print("selected origin/master")
                            throw new Exception("Tag selection is required")
                        }
                        
                    }catch (err) {
                        echo "Caught: ${err}"
                        currentBuild.result = 'FAILURE'
                    }
                }

                checkout scm: [$class: 'GitSCM', 
                    userRemoteConfigs: [[url: "${env.APP_REPO_URL}",
                                         credentialsId: "${env.GITHUB_CREDENTIAL_ID}"]],
                    branches: [[name: "refs/tags/${params.TAG_NAME}"]]], 
                    poll: false
            }
        }
        stage('Build Source Code'){
            steps {
                sh "pwd"
                sh './gradlew build'
            }
        }
        stage('Build docker image') {
            steps {
                script {
                    print("execute script docker image")
                    // createDockerImage()
                    try {
                        //sh "cp -rf ${home}/$buildDir $destDir" // war 파일을 현재 위치로 복사 
                        //sh "cp ${home}/$srcDir/Dockerfile $destDir" // Dockerfile
                        sh "docker build --platform linux/amd64 -t $repository:$BUILD_NUMBER ."
                        sh "docker build --platform linux/amd64 -t $repository:latest ."
                    } catch (error) {
                        echo "[createDockerImage call()] Error ::: ${error}"
                    }
                }
            }
        }
        stage('Login') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
            }
        }
        stage('Deploy our image') {
            steps {
                script {
                    sh 'docker push $repository:$BUILD_NUMBER' //docker push
                    sh 'docker push $repository:latest' //docker push
                }
            }
        }
        stage('Cleaning up') {
            steps {
                sh "docker rmi $repository:$BUILD_NUMBER" // docker image 제거
                sh "docker rmi $repository:latest" // docker image 제거
            }
        }
        stage('Start Application as Docker') {
            steps {
                sshagent (credentials: ['controller-ssh-private-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${TARGET_HOST} '
                    pwd
                    docker-compose down
                    docker rmi ${repository}:latest
                    docker-compose up -d
                    '
                """
                }
            }
        }
    }
}