#!groovy
@Library('common-api') _

pipeline {

    agent any 

    environment {
        GIT_REPO_URL = 'https://github.com/jinho-yoo-jack/fastcampus-ci-cd.git'
        repository = "jhy7342/cicd-study"  //docker hub id와 repository 이름
        DOCKERHUB_CREDENTIALS = credentials('DockerHub') // jenkins에 등록해 놓은 docker hub credentials 이름
        dockerImage = '' 
    }

    parameters {
        // TODO: Must modify BRANCH_NAME to TAG_NAME
        choice(name: 'BRANCH_NAME', choices: getBranchList('https://github.com/jinho-yoo-jack/fastcampus-ci-cd.git'))

    }

    stages {
        stage('git clone'){
            steps {
                echo "git clone"
                git branch: 'feature/docker', credentialsId: 'ea380414-e517-45cb-91dc-882c64c04255', url: "${GIT_REPO_URL}"
                sh "docker pull"
            }
        }
        stage('build'){
            steps {
                sh './gradlew build'
            }
        }
        stage('Test') {
            steps {
                script {
                    sh "docker --version"
                    sh "docker compose --version"
                }
            }
        }
        stage('dockerizing'){
            steps {
                sh 'echo "docker build"'
                sh "docker build -t ${repository}:1.0.0 ."
            }

        }
        stage('Re-Execute Application'){
            steps {
                sh 'echo "Execute"'
            }

        }
    }
}