#!groovy
@Library('common-api') _

pipeline {

    agent any 

    tools {
        git 'git'
        gradle 'gradle-8.9'
        jdk 'jdk-21'
    }

    environment {
         GIT_REPO_URL = 'https://github.com/jinho-yoo-jack/fastcampus-ci-cd.git'
    }

    parameters {
        // TODO: Must modify BRANCH_NAME to TAG_NAME
        choice(name: 'BRANCH_NAME', choices: getBranchList('https://github.com/jinho-yoo-jack/fastcampus-ci-cd.git'))
    }

    stages {
        stage('git clone'){
            steps {
                echo "git clone"
                git branch: 'master', credentialsId: 'ea380414-e517-45cb-91dc-882c64c04255', url: "${GIT_REPO_URL}"
            }
        }
        stage('build'){
            steps {
                sh './gradlew build'
            }
        }
        stage('Deploy'){
            steps {
                sh 'echo "Deploy"'
            }

        }
        stage('Re-Execute Application'){
            steps {
                sh 'echo "Execute"'
            }

        }
    }
}